---
repository:
  description: Start the iDAC6 virtual console on the DELL PowerEdge R610 without the need of Java Web Start or accessing it from the web interface.
  homepage: https://mesd.ag/
  topics: github, backup
